// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/tehrelt/workmate-testovoe/internal/models"

	uuid "github.com/google/uuid"
)

// TaskProvider is an autogenerated mock type for the TaskProvider type
type TaskProvider struct {
	mock.Mock
}

// Task provides a mock function with given fields: ctx, id
func (_m *TaskProvider) Task(ctx context.Context, id uuid.UUID) (*models.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Task")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Tasks provides a mock function with given fields: ctx, filter
func (_m *TaskProvider) Tasks(ctx context.Context, filter *models.TaskFilter) (<-chan *models.Task, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Tasks")
	}

	var r0 <-chan *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TaskFilter) (<-chan *models.Task, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.TaskFilter) <-chan *models.Task); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.TaskFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskProvider creates a new instance of TaskProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskProvider {
	mock := &TaskProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
