// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/tehrelt/workmate-testovoe/internal/models"
)

// TaskSaver is an autogenerated mock type for the TaskSaver type
type TaskSaver struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, task
func (_m *TaskSaver) Save(ctx context.Context, task *models.CreateTask) (*models.Task, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateTask) (*models.Task, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateTask) *models.Task); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateTask) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskSaver creates a new instance of TaskSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskSaver {
	mock := &TaskSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
